language: go
go:
- 1.8
dist: trusty
sudo: required
notifications:
  slack:
    secure: uezT1E7kSVRDC2El9g5syXb1I4JrUUJHW4PXAf0IhXDFqS1ewkrNMurbkltrsJp0OtH7r2rzewuZsxjZ8pz0D+9YPorQzCPUgSqHuYnplh5WJMiaImXVvyApOpVEIm/0mFitrhfGjtMDXegRw1Rk95ujKNokulCSlLqGT1GSKQXmRjBgPYPqPmWQUbzkvwgL6NcMODv1GLyslGGTVKY/WiSjYkiNsQbDjxED3w5rAoX1FG3pvcHAXGxSWbTEk2VzvjGuNwflK92FZZXS/NxXPdEa4lPjlFBRRTHWwEXS4qbaGrdQNJ1DFI/QWrKtw6sHpqt22ovXEk4qkVthaf6Yq8YxoBQ80ajY6gw72ZMXreN3AaHCi7thNKtj/v2e1qlxggNCA8WDnXQmQ0iCg+BYD63LsVbJqlAGq151GGGJXSTcci1DhsuT3JeYx2Vd+wIHNTuYRqFJACnA45KRyExejyzdAYvdBgMnbMbtKctKtFthB5g5P1evBvx/PmZxpXPxIhLKjlCwZgutfR2jy1YSFjIHDR3hBJGsPj1z0XLo36kTOUM/CpTzbNFe2xr3dZrNH/LwWiYO9NBeCHc6kCi6DKi7X7bvnlpk8tazHep7VDQputNWgwEu4flld8jy7QRnIDVIj+4qwT+YhUDG/2lPJ5/Agxjq7rGgkIpPc8Kd8sQ=
addons:
  artifacts:
    paths:
    - cmd/dgraph
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - libbz2-dev
    - libsnappy-dev
    - zlib1g-dev
    - jq
    - graphviz
  hosts:
  - server1.dgraph.io
  - server2.dgraph.io
env:
  matrix:
  - CC=clang-3.9 CXX=clang++-3.9
  global:
    # GH_TOKEN
    secure: Kj7Y1beeorefXbpLWK+kgJEmwBFw69TgYcXcYCOt2W8kQFIJXom8QqEt8/BcYrhc0dI41J/x/abt/XSRUqCg6IsFwJiVZusVVRKl4IDC6i43CoLWudObp7u7eqZ+FBLin/YxpRFB/btYYiblmDSlSvO09nSODzaDaUTfyEqjAxBgOVK+DHDwCXaGVAaZsBd8JTVRkkO9uGqMRDPmEgDMbv6S9Pmfjb5/p2Om8OCnNZNgsglJMVNWFjVYE1pxxcSsgnNrIcQGx1X5qPcX4OHcR1DfsgmwrZ/Jz/Hl0RmCljpPZeAk2BW4zi6LkHZr0K6kOrXasqfAZwlBUd6RtMZLpHOlgwXCXL4hHQEtF6PmyaICuwucv90vcLrAbIWVZBEa0vtPpkZiNCb2Lb0aaT1R+boBravWLzlsqB8xDuvpewe3pLNrDwU1COFKdEJT0T8mZ7RVHEPGU9jjg+j4rmQElRIbyifQp300XVCcD3xoful/ONdx8ljOk7Has2aRFmwpCZrRV06SrPgkfceIgIv9rQidoy2K/JbFjDkcqZxTC/hKaSm0ZSjf4oBs2RK4XkKK9z296B+cyfy4PFyGFYKJPjjMbn3WQmG+ojp/GbW6M84CTAjB9GxSIHQtQjkZkJ95xa25fMYIrPFAaFeMKpcHocqp5OW0HyEv+JWJ0ObkP0Q=
cache:
  apt: true
  directories:
  - "$HOME/build"
install:
- bash contrib/build-rocksdb.sh $HOME/build
before_script:
- go get github.com/mattn/goveralls
script:
- contrib/nightly/build.sh
