language: go
go:
- 1.8
dist: trusty
sudo: required
notifications:
  slack:
    secure: uezT1E7kSVRDC2El9g5syXb1I4JrUUJHW4PXAf0IhXDFqS1ewkrNMurbkltrsJp0OtH7r2rzewuZsxjZ8pz0D+9YPorQzCPUgSqHuYnplh5WJMiaImXVvyApOpVEIm/0mFitrhfGjtMDXegRw1Rk95ujKNokulCSlLqGT1GSKQXmRjBgPYPqPmWQUbzkvwgL6NcMODv1GLyslGGTVKY/WiSjYkiNsQbDjxED3w5rAoX1FG3pvcHAXGxSWbTEk2VzvjGuNwflK92FZZXS/NxXPdEa4lPjlFBRRTHWwEXS4qbaGrdQNJ1DFI/QWrKtw6sHpqt22ovXEk4qkVthaf6Yq8YxoBQ80ajY6gw72ZMXreN3AaHCi7thNKtj/v2e1qlxggNCA8WDnXQmQ0iCg+BYD63LsVbJqlAGq151GGGJXSTcci1DhsuT3JeYx2Vd+wIHNTuYRqFJACnA45KRyExejyzdAYvdBgMnbMbtKctKtFthB5g5P1evBvx/PmZxpXPxIhLKjlCwZgutfR2jy1YSFjIHDR3hBJGsPj1z0XLo36kTOUM/CpTzbNFe2xr3dZrNH/LwWiYO9NBeCHc6kCi6DKi7X7bvnlpk8tazHep7VDQputNWgwEu4flld8jy7QRnIDVIj+4qwT+YhUDG/2lPJ5/Agxjq7rGgkIpPc8Kd8sQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - libbz2-dev
    - libsnappy-dev
    - zlib1g-dev
    - jq
    - graphviz
  hosts:
  - server1.dgraph.io
  - server2.dgraph.io
env:
  matrix:
  - CC=clang-3.9 CXX=clang++-3.9
  global:
  - secure: VkBvETNHIhgegl3tLYI3fqDKD8CdZiYMgDCT1vetInyFjB2OQElOLD9TUwtTdWPoo9Oc/GiLJsx29yWAEVbw4nToyULDv8IbNV2IVA2FiQPijhLlwaiQxE3cbgo6e572C/SO+w2DVdBsBO+wFDhm8lj0/P9C+eBbRvEp0oBBKjDfR7yb3/YKi1S8WxGCHK4lMMlYKPc2s8RTIdGh+5ChQmQVp3ve0zEdmq5rCLwS5BbzNw21iw3Cw1/AyaBeKyNH8wNVg7QqxX56LIWFtcu03uz+l7PQDfFsaZo4Gsu1iYBO7aZcwlBwVxQr6L0dHzQy4KSpk6tHOQycDEDM+gMPe7RMJxEqwtRCa8ffNn2uXWp1MyXTUhSgqzQ1TWcZaFn/7V+KXNZJYNA2OT1TPodNblunMKwzth8XxyCGMhSeXb2ZsTxotzZ9GEBwwa9YA/5dHYfY+zKDhcMlLUFipqq3e9sfY3eMX1kg6rhYk0snBFYrf2X6d7Ug0+EF9pYsRHs9IqY8uQTyMHDNSzKzRrJjLyVX3/XORQHDjiVGrxXkf+3lWj3Dz76NfD8ZJwnx2ecYG81jgdB/Jt5Rsn5UrIw2Q95c0AqqZX17p1/Ws+g4A8rPyJlaSIsrnICRnXIrxHdVrgqNFxS/24SvaWLCjycdz2nM1RlssIaTu/J99G/WpJI=
cache:
  apt: true
  directories:
  - "$HOME/build"
install:
- bash contrib/build-rocksdb.sh $HOME/build
before_script:
- go get github.com/mattn/goveralls
script:
- contrib/nightly/build.sh
